name: Deploy to uat
on:
  push:
    paths:
      - 'teams-alert.sh'    
jobs:
  build:
    runs-on: ubuntu
    steps:
    - uses: actions/checkout@v1
      with:
        ref: master
    - name: deploy to uat
      run: sh teams-alert.sh 
